import { TECHNOLOGIES } from '../core/technology.ts';
import { duration, escape, number } from './format.ts';
import type { Universe } from '../core/types.ts';
export function civilizationPanel(state: Universe): string {
  const civilizations = Object.values(state.civilizations).sort((a, b) => Number(b.followed) - Number(a.followed));
  return `<div class="eyebrow">THEIR STORY IS THEIR OWN</div><h2>Living worlds</h2><p>Watch cultures choose their own path. Follow a civilization to collect its moments.</p><div class="cards">${civilizations.map(civ => `<article class="card"><div class="card-title"><strong>${escape(civ.name)}</strong><span class="badge">${civ.status === 'extinct' ? 'Ruins' : `Level ${civ.level}`}</span></div><p>${escape(state.objects[civ.planetId].name)} · ${escape(civ.government)} · ${civ.traits.join(' · ')}</p><div class="metrics"><div class="metric"><span>Population</span><strong>${number(civ.population)}</strong></div><div class="metric"><span>Age</span><strong>${duration((civ.status === 'active' ? state.time : civ.lastUpdate) - civ.foundedAt)}</strong></div><div class="metric"><span>Stability</span><strong>${Math.round(civ.stability * 100)}%</strong></div><div class="metric"><span>Science</span><strong>${Math.round(civ.science * 100)}%</strong></div></div><p>${civ.researching ? `Researching ${TECHNOLOGIES[civ.researching].name} · ${number(civ.researchPoints)} / ${number(TECHNOLOGIES[civ.researching].cost)}` : civ.status === 'extinct' ? 'Only memories and artifacts remain.' : 'Preparing their next question.'}</p><div class="button-row"><button data-action="select" data-value="${civ.planetId}">Observe world</button><button data-action="follow" data-value="${civ.id}" aria-pressed="${civ.followed}">${civ.followed ? 'Following' : 'Follow'}</button></div><details data-details-key="${escape(civ.id)}"><summary>History · ${civ.timeline.length} moments</summary><ol class="timeline">${[...civ.timeline].reverse().slice(0, 20).map(event => `<li><small>${duration(event.time - civ.foundedAt)} after emergence</small><strong>${escape(event.title)}</strong><p>${escape(event.detail)}</p></li>`).join('')}</ol></details></article>`).join('') || '<article class="card"><h3>The first curious minds</h3><p>Give a world a stable atmosphere, water and a diverse ecosystem. Intelligence will emerge naturally.</p></article>'}</div>`;
}
export function researchPanel(state: Universe): string {
  const civ = Object.values(state.civilizations).find(c => c.planetId === state.selectedId) ?? Object.values(state.civilizations)[0];
  return `<div class="eyebrow">ONE QUESTION LEADS TO ANOTHER</div><h2>Paths of knowledge</h2><p>${civ ? `${escape(civ.name)} chooses research according to its strengths. Select another world to see a different path.` : 'Civilizations research independently once intelligence emerges.'}</p><div class="cards">${Object.entries(TECHNOLOGIES).map(([id, tech]) => `<article class="card"><div class="card-title"><strong>${tech.name}</strong><span class="badge">${civ?.technologies.includes(id) ? 'Known' : civ?.researching === id ? 'Researching' : tech.domain}</span></div><p>${tech.description}</p><small class="muted">${number(tech.cost)} knowledge${tech.requires.length ? ` · Needs ${tech.requires.map(id => TECHNOLOGIES[id].name).join(', ')}` : ''}</small></article>`).join('')}</div>`;
}
