import { BALANCE, STELLAR_BALANCE } from '../core/config.ts';
import { hasTechnology } from '../simulation/civilizations.ts';
import { canAfford } from '../simulation/economy.ts';
import { button } from './panels.ts';
import { costText, duration, escape } from './format.ts';
import type { Universe } from '../core/types.ts';
export function explorationPanel(state: Universe): string {
  const job = state.exploration.job;
  return `<div class="eyebrow">WHAT LIES JUST BEYOND?</div><h2>A little farther</h2><p>Survey space. Every expedition continues while you are away.</p>${job ? `<article class="card"><strong>${job.kind} expedition</strong><progress aria-label="Expedition progress" value="${state.time - job.startedAt}" max="${job.endsAt - job.startedAt}"></progress><p>Returning in ${duration(Math.max(0, job.endsAt - state.time))}</p></article>` : ''}<div class="cards"><article class="card"><h3>Orbital expedition</h3><p>Discover moons, new worlds and mineral-rich asteroids. Requires two planet upgrades.</p>${button(`Launch · ${costText(BALANCE.exploration.cost)}`, 'explore', 'orbital', !!job || state.totalUpgrades < 2 || !canAfford(state, BALANCE.exploration.cost))}</article><article class="card"><h3>To another star</h3><p>New systems hold different stars and unfamiliar worlds. Requires Spaceflight.</p>${button(`Launch · ${costText(STELLAR_BALANCE.interstellarCost)}`, 'explore', 'interstellar', !!job || !hasTechnology(state, 'spaceflight') || !canAfford(state, STELLAR_BALANCE.interstellarCost))}</article></div><h3>Known systems</h3><div class="cards">${Object.values(state.systems).map(system => `<article class="card"><div class="card-title"><strong>${escape(system.name)}</strong><span class="badge">${state.objects[system.starId].stellar?.stage}</span></div><p>${state.objects[system.starId].stellar?.class} · ${state.objects[system.starId].children.length} orbiting bodies</p>${button('Visit system', 'select', state.objects[system.starId].children.find(id => state.objects[id].planet) ?? system.starId, false, true)}</article>`).join('')}</div><h3>Local discoveries</h3><div class="cards">${Object.values(state.objects).filter(o => o.systemId === state.objects[state.selectedId].systemId && !o.stellar).map(o => `<article class="card"><div class="card-title"><strong>${escape(o.name)}</strong><span class="badge">${o.type}</span></div><div class="button-row">${button('Observe', 'select', o.id, false, true)}${o.type === 'asteroid' && !o.mined ? button('Mine · 60 energy / 25 matter', 'mine', o.id, !canAfford(state, { energy: 60, matter: 25 })) : ''}</div></article>`).join('')}</div>`;
}
