import { BALANCE, GALAXY_BALANCE, STELLAR_BALANCE } from '../core/config.ts';
import { hasTechnology } from '../simulation/civilizations.ts';
import { canDetailSystem } from '../gameplay/systems.ts';
import { canAfford } from '../simulation/economy.ts';
import { button } from './panels.ts';
import { costText, duration, escape, number } from './format.ts';
import type { Universe } from '../core/types.ts';
export function explorationPanel(state: Universe): string {
  const job = state.exploration.job;
  const galaxy = state.galaxies[state.systems[state.objects[state.selectedId].systemId].galaxyId];
  return `<div class="eyebrow">WHAT LIES JUST BEYOND?</div><h2>A little farther</h2><p>Survey space. Every expedition continues while you are away.</p>${job ? `<article class="card"><strong>${job.kind} expedition</strong><progress aria-label="Expedition progress" value="${state.time - job.startedAt}" max="${job.endsAt - job.startedAt}"></progress><p>Returning in ${duration(Math.max(0, job.endsAt - state.time))}</p></article>` : ''}<div class="cards"><article class="card"><h3>Orbital expedition</h3><p>Discover moons, new worlds and mineral-rich asteroids. Requires two planet upgrades.</p>${button(`Launch · ${costText(BALANCE.exploration.cost)}`, 'explore', 'orbital', !!job || Object.keys(state.objects).length >= BALANCE.maxObjects || state.totalUpgrades < 2 || !canAfford(state, BALANCE.exploration.cost))}</article><article class="card"><h3>To another star</h3><p>New systems hold different stars and unfamiliar worlds. Requires Spaceflight.${!canDetailSystem(state) ? ' Distant sector surveys add 75 knowledge.' : ''}</p>${button(`Launch · ${costText(STELLAR_BALANCE.interstellarCost)}`, 'explore', 'interstellar', !!job || galaxy.surveyed >= galaxy.totalSystems || !hasTechnology(state, 'spaceflight') || !canAfford(state, STELLAR_BALANCE.interstellarCost))}</article><article class="card"><h3>Beyond the galaxy</h3><p>Chart a new reach. Requires Interstellar travel.</p>${button(`Launch · ${costText(GALAXY_BALANCE.cost)}`, 'explore', 'galactic', !!job || Object.keys(state.galaxies).length >= GALAXY_BALANCE.maxGalaxies || !hasTechnology(state, 'interstellar') || !canAfford(state, GALAXY_BALANCE.cost))}</article></div><h3>Known systems</h3><div class="cards">${Object.values(state.systems).map(system => `<article class="card"><div class="card-title"><strong>${escape(system.name)}</strong><span class="badge">${state.objects[system.starId].stellar?.stage}</span></div><p>${state.objects[system.starId].stellar?.class} · ${state.objects[system.starId].children.length} orbiting bodies</p>${button('Visit system', 'select', state.objects[system.starId].children.find(id => state.objects[id].planet) ?? system.starId, false, true)}</article>`).join('')}</div><h3>Local discoveries</h3><div class="cards">${Object.values(state.objects).filter(o => o.systemId === state.objects[state.selectedId].systemId && !o.stellar).map(o => `<article class="card"><div class="card-title"><strong>${escape(o.name)}</strong><span class="badge">${o.type}</span></div>${o.type === 'asteroid' ? `<p>${o.mined ? 'Mining outpost active.' : `Recover ${number(o.deposit)} minerals, then supply more over time.`}</p>` : ''}<div class="button-row">${button('Observe', 'select', o.id, false, true)}${o.type === 'asteroid' && !o.mined ? button(`Mine · ${costText(BALANCE.asteroidCost)}`, 'mine', o.id, !canAfford(state, BALANCE.asteroidCost)) : ''}</div></article>`).join('')}</div>`;
}
