import { canRebirth, lawCost, MODIFIERS, rebirthReward } from '../gameplay/prestige.ts';
import { offlineCap } from '../core/meta.ts';
import { hasTechnology } from '../simulation/civilizations.ts';
import { automationStatus } from '../gameplay/automation.ts';
import type { LawId, Universe } from '../core/types.ts';
import { button, metric } from './panels.ts';
import { duration, escape } from './format.ts';
export function prestigePanel(state: Universe): string {
  const laws: Record<LawId, [string, string]> = { production: ['Abundant creation', '+15% production per level.'], evolution: ['Living possibility', '+10% evolution per level.'], research: ['Curious minds', '+12% research per level.'], offline: ['Enduring time', 'One more day of offline progress per level, up to seven days.'] };
  return `<div class="eyebrow">EVERY END IS A BEGINNING</div><h2>Another Big Bang</h2><div class="metrics">${metric('Rebirths', String(state.meta.runs))}${metric('Cosmic Knowledge', String(state.meta.cosmicKnowledge))}${metric('Next rebirth reward', String(rebirthReward(state)))}${metric('Offline horizon', duration(offlineCap(state)))}</div><article class="card"><h3>Carry the universe with you</h3><p>Rebirth resets your worlds, civilizations, technology, local resources and construction. Keep discoveries, achievements, artifacts, records, settings and universal laws.</p><p>Build a completed Dyson swarm to unlock rebirth.</p><label>Next universe seed (optional)<input id="rebirth-seed" type="number" min="0" max="4294967295" placeholder="A new deterministic seed"></label><h3>Choose up to two new conditions</h3>${Object.entries(MODIFIERS).map(([id, m]) => `<label class="toggle"><input type="checkbox" data-modifier="${id}" ${state.meta.nextModifiers.includes(id) ? 'checked' : ''} ${state.meta.runs + 1 < m.runs ? 'disabled' : ''}>${escape(m.name)}${state.meta.runs + 1 < m.runs ? ` · rebirth ${m.runs}` : ''}</label><p>${m.description}</p>`).join('')}${button(`Rebirth · earn ${rebirthReward(state)} Cosmic Knowledge`, 'rebirth', '', !canRebirth(state))}</article><h3>Universal laws</h3><div class="cards">${(Object.keys(laws) as LawId[]).map(id => `<article class="card"><div class="card-title"><strong>${laws[id][0]}</strong><span class="badge">Level ${state.meta.laws[id]}</span></div><p>${laws[id][1]}</p>${button(`${lawCost(state, id)} Cosmic Knowledge`, 'law', id, state.meta.laws[id] >= 20 || state.meta.cosmicKnowledge < lawCost(state, id))}</article>`).join('')}</div><h3>Let your worlds help themselves</h3><article class="card"><p>AI unlocks optional automation every minute of universe time, including while you are away. Exploration saves for the best reachable destination. Development balances affordable upgrades on the selected world or a planet in its system. Other automations protect funds for an expedition waiting to launch. Mining establishes one outpost per minute, prioritizing the selected asteroid, its system, then the richest deposit. Research keeps at least 200 knowledge in reserve.</p>${Object.entries(state.automation).map(([id, enabled]) => `<label class="toggle"><input type="checkbox" data-automation="${id}" ${enabled ? 'checked' : ''} ${!hasTechnology(state, 'ai') ? 'disabled' : ''}>Automatic ${id === 'assist' ? 'civilization assistance' : id === 'develop' ? 'planet development' : id === 'research' ? 'research inspiration' : id === 'mine' ? 'asteroid mining' : 'exploration'}</label><p data-automation-status="${id}">${escape(automationStatus(state, id as keyof Universe['automation']))}</p>`).join('')}</article>`;
}
